export CUDA_VISIBLE_DEVICES=0
model_name=SimpleTM


python3 -u run.py \
  --is_training 1 \
  --lradj TST \
  --patience 3 \
  --root_path ../dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 1 \
  --d_model 32 \
  --d_ff 32 \
  --learning_rate 0.006 \
  --batch_size 256 \
  --use_norm 1 \
  --wv bior3.1 \
  --m 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des Exp \
  --itr 1 \
  --alpha 0.3 \
  --l1_weight 0.0005 \
  --clusterGNN True \
  --num_clusters 6


python3 -u run.py \
  --is_training 1 \
  --root_path ../dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_192 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --e_layers 1 \
  --d_model 32 \
  --d_ff 32 \
  --learning_rate 0.006\
  --batch_size 256 \
  --use_norm 1 \
  --wv "bior3.1" \
  --m 1 \
  --alpha 0.0 \
  --l1_weight 0.005 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --d_model 128 \
  --d_ff 128 \
  --itr 1 \
  --clusterGNN True \
  --num_clusters 6

python3 -u run.py \
  --is_training 1 \
  --root_path ../dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_336 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 336 \
  --e_layers 1 \
  --d_model 64 \
  --d_ff 64 \
  --learning_rate 0.006\
  --batch_size 128 \
  --wv "bior3.3" \
  --alpha 0.6 \
  --l1_weight 5e-5 \
  --m 1 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --itr 1 \
  --clusterGNN True \
  --d_model 128 \
  --d_ff 128 \
  --num_clusters 6

python3 -u run.py \
  --is_training 1 \
  --root_path ../dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_720 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --e_layers 1 \
  --d_model 96 \
  --d_ff 96 \
  --learning_rate 0.003\
  --batch_size 256 \
  --wv "db1" \
  --m 3 \
  --alpha 1.0 \
  --l1_weight 0.0 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --d_model 128 \
  --d_ff 128 \
  --itr 1 \
  --clusterGNN True \
  --num_clusters 6